name: simple-flask-app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: winpty docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
 
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag simple-flask-app:$(date +%s)
      
    - name: Docker Push
      run: docker push e0552/CI-CD-enabled-flask-app
